tunnel: f76f27e8-bca5-4839-ac3c-7203be99e006
credentials-file: /etc/cloudflared/cred.json

ingress:
  - hostname: lexicompanion.com
    service: http://lex-traefik-1:80
  - hostname: api.lexicompanion.com
    service: http://lex-traefik-1:80
  - service: http_status:404
